services:
  enabled: true
  system:
    - bluetooth.service
    - upmpdcli.service
  user:
    - mpd.service
    - pipewire-pulse.service
    - pulseaudio.service
    - shairport-sync.service
    - snapclient.service
    - spotifyd.service

pulseaudio:
  enabled: true

mpris:
  enabled: true
  timeout: 5s

api:
  enabled: true
  port: 8080

logLevel: warn
