bind: lo
logLevel: info

api:
  enabled: true
  port: 8018

zeroconf:
  enabled: false

systemd:
  enabled: false
  system:
    - bluetooth.service
    - upmpdcli.service
  user:
    - mpd.service
    - pipewire-pulse.service
    - pulseaudio.service
    - shairport-sync.service
    - snapclient.service
    - spotifyd.service

pulseaudio:
  enabled: true

mpris:
  enabled: true
  timeout: 5s

bluetooth:
  enabled: true
  timeout: 5s
  pairingTimeout: 60s
